version: '3.3'

services:
  node:
    container_name: calne_backend
    restart: always
    image: node:16.10.0
    ports: 
      - 3013:3013
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks: 
      - calne_network
  
    command: bash -c "npm install && npm run start:prod"

networks:
  calne_network:
    driver: bridge